# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main , 'staging**']

jobs:
  quality:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm test
  # nextVersionCheck:

  #   runs-on: ubuntu-latest
  #   needs: [quality]
  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: Use Node.js ${{ matrix.node-version }}
  #     uses: actions/setup-node@v2
  #     with:
  #       node-version: ${{ matrix.node-version }}
  #       cache: 'npm'
  #   - run: npm ci
  #   - run: ./scripts/find_next_version.sh
  #     env: 
  #        NPM_TOKEN: ${{secrets.NPM_TOKEN }}
  #        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
  publish:

    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' || contains(github.ref, 'staging')}}
    needs: [quality]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: Update tags
      run: ./scripts/update_tags.sh
      env: 
         GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
    - run: npm ci 
    - run: npm run semantic-release 
      env: 
         NPM_TOKEN: ${{secrets.NPM_TOKEN }}
         GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
