# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  pull_request:
    branches: '*'


jobs:
  quality:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm test
    - name: Validate PR title
      uses: amannn/action-semantic-pull-request@v3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

# name: "Lint PR"

# on:
#   pull_request_target:
#     types:
#       - opened
#       - edited
#       - synchronize

# jobs:
#   main:
#     name: Validate PR title
#     runs-on: ubuntu-latest
#     steps:
#       - uses: amannn/action-semantic-pull-request@v3
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


